pmndrs/racing-game

src/styles.css
src/ui/Controls.js

improved controls help

---

src/models/Vehicle.js
src/ui/Controls.js
src/utils/store.js

- Default _(from behind the car)_
- First Person _(from the cockpit)_
- Birds Eye _(from the top of the car)_

Add camera types

---

src/App.js

Added the drei loader, might do something custom later with useProgress()

drei loader

---

.gitignore
src/styles.css
src/ui/Speed.js
src/ui/svgs/speedmeter/background.js
src/ui/svgs/speedmeter/foreground.js

The gauge is made of 2 SVGs:
The animation is done by applying a linear gradient on the background SVG and changing the offset property.

Add speed gauge

---

README.md
package.json
public/index.html

`README.md`:
- Capitalize sentences
- Link to demo redirects to `http` so we can link to that directly
- Link directly to the `#proj-racing-game` channel on the Poimandres discord server
- Reword `the app store` to `game state store`
- HUD stands for `heads up display`
- Add a title above the image
`package.json`:
- Updated the title to `@pmndrs/racing-game` to be consistent with the repo
- Updated the description to match the repo (and of course add an emoji racecar 🏎️)
`index.html`:
- Page title matches app title: `@pmndrs/racing-game`
- `theme-color` matches ground color from the track

Make the app title consistent

---

.eslintrc.json
src/App.js
src/controls/KeyboardControls.js
src/enums.js
src/models/vehicle/Chassis.js
src/models/vehicle/Vehicle.js
src/models/vehicle/Wheel.js
src/store.js
src/ui/Editor.js
src/ui/Speed.js

These aren't really constants if we are changing them.
We can move `vehicleConfig` to the root of the store.
Also `cameraType` can move out of controls as it's not a key we are using to control the car.

[Refactor] Remove constants from store

---

.github/workflows/nodejs.yml

It seems like it was promised but got lost in time: https://github.com/pmndrs/racing-game/pull/41#issue-661413394

Run prettier as workflow

---

src/models/track/Heightmap.js
src/models/vehicle/Vehicle.js

This should fix the CI errors.

Run prettier fix

---

src/ui/Editor.js

Folder: General - General options to change about the vehicle nothing advanced
Folder Raycasting - Used to group the settings to control the information/dynamics of the wheels.
Folder Misc - Mostly buttons just yeah no real purpose to the game engine in that kind of sort.

Add folder into editor settings

---

src/App.js
src/controls/Inactivemouse.js

This will hide the mouse after it hasn't been moved for 3 seconds and re-appear when the user moves it again.

Hide mouse after 3 seconds inactivity

---

.eslintrc.json
.gitignore
.prettierignore
package.json

Some little bits of #76 that got missed when it was clobbered.

Enable jsx for eslint

---

src/controls/Keyboard.js

We were registering 2 * 12 event handlers, now we only register 2.

Use a single eventHandler for keydown and keyup

---

src/ui/Help.jsx

Fix small regression to toggle help menu.

fix: help menu regression

---

README.md

Made sure that the expiry is set to never and unlimited uses

New discord invite

---

src/controls/Keyboard.js

Especially notice-able when you somehow get an editor screen when you type your name on the leader board.

Don't watch keystrokes on input element

---

package.json

Doesn't really affect anything, but it could be annoying in the future.

[package.json] main should be src/main.jsx

---

src/styles.css
src/ui/Minimap.jsx

Fixes #118
This PR focuses only on the placement of elements, but might look att improving the indivudual elements in follow up PRs

feat: update placement of HUD elements

---

src/models/vehicle/Vehicle.jsx

I realized user is able to drive the car behind the intro screen :)

Disable vehicle controls on intro screen

---

src/models/vehicle/Vehicle.jsx

Using an offset modulo function, I've tried to create an output similar to this: 
Due to the nature of modulo functions, gears are evenly spaced, so in future we can use speed to calculate the current gear if needed. So if we had 6 gears, maxSpeed 120mph, this would result in 20mph per gear; 40mph would be the speed when changing from 2nd to 3rd gear.

make engine sound like gears

---

.eslintrc.json
package.json
src/App.tsx
src/data.ts
src/store.ts
yarn.lock

Code Quality to the win. I will add some more rules later but this is mostly to fix up the workflow of eslint to play nice with Typescript.

Fix Eslint & Add typescript Eslint & add some rules

---

package.json

small fix but better to organize dependencies at proper places.

move @types/three to devDependencies

---

src/data.ts
src/ui/Finished.tsx
src/ui/LeaderBoard.tsx

- [Data] Always return an array so we can skip null checks
- [LeaderBoard] Create Scores component instead of recreating the UL every time.

[TS] Differentiate between saved and unsaved scores

---

src/App.tsx
src/models/Goal.ts
src/styles.css
src/ui/Clock.tsx
src/ui/Finished.tsx
src/ui/Speed.tsx

- Use `requestAnimationFrame` to help batch our updates to the UI
- Avoid updating the DOM unless there are changes
- The finish line no longer continuously updates your score after you've crossed it

[UI] Use requestAnimationFrame to update

---

src/ui/Clock.tsx
src/ui/Speed.tsx

@drcmda That worked great. Thanks for the tip!

Use r3f's addEffect instead of requestAnimationFrame

---

src/models/vehicle/Vehicle.tsx

In this `if` statement it will always be `true`.

remove useless condition

---

src/ui/Minimap.tsx

The player position was not updated anymore.

fix: minimap player position

---

package.json
yarn.lock

Remove @react-three/postprocessing

---

README.md
src/controls/Keyboard.ts
src/ui/Help.tsx

I thought we could add a few controls for Azerty users. So I added Z for forward & Q for left movements.
I also added an indication of the new controls in the `Help.tsx` component so that users can see it when they launch the game.

Azerty controls

---

src/App.tsx
src/store.ts
src/styles.css
src/ui/Checkpoint.tsx

The data doesn't change frequently and we can do it with 2 properties instead of 4.
Having the setTimeout as an effect of the component also means it can clean itself up.

Move checkpoint data from mutation to store

---

src/store.ts
src/ui/Clock.tsx
src/ui/Speed/Boost.tsx
src/ui/Speed/Gauge.tsx
src/ui/Speed/Text.tsx

These values don't change often, finish was a duplicate of finished.
Refactored UI useEffect calls to compare against DOM values to prevent react from getting out of sync with the DOM.

Move finish & start out of mutation

---

src/App.tsx
src/useToggle.tsx

Updated useToggle to allow components with children

useToggle for Debug

---

src/effects/Boost.tsx
src/models/vehicle/Chassis.tsx
src/models/vehicle/Vehicle.tsx
src/store.ts

Used non reactive method of getting state for states that weren't used by effects or didn't need a rerender

Optimize renders

---

src/App.tsx
src/effects/Cameras.tsx
src/effects/index.ts
src/models/vehicle/Vehicle.tsx

1. resolves #181 
The bug was caused by App.tsx re-rendering when camera updates
2. resolves #175 
removed unnecessary useLayoutEffect and adjusted rotational math

fix: reset on camera change

---

src/models/vehicle/Chassis.tsx

We need to pass the unsubscribe function to layoutEffect

Unsubscribe from velocity updates

---

src/App.tsx
src/models/BoundingBox.tsx
src/models/index.ts

Reset the player if they exceed the bounds of the map

---

tsconfig.json

[tsconfig] Remove allowJs

---

package.json
src/models/Ramp.tsx
yarn.lock

The hard part was already done in the last PR :)

Update @react-three/cannon to v6.3.0
